### ISSUE TITLE
'MockApp' object has no attribute 'config'

### ISSUE THREAD

**Issue by ssh4root** [noraj/flask-session-cookie-manager#15] opened 2024-12-26 15:00 UTC
![err](https://github.com/user-attachments/assets/883faec7-8fb4-4bcb-9c20-6223765c0a08)
root@hcss-ecs-b9f5:/home/lu/flask-session-cookie-manager# python3 -m venv venvNew
root@hcss-ecs-b9f5:/home/lu/flask-session-cookie-manager# source venvNew/bin/activate
(venvNew) root@hcss-ecs-b9f5:/home/lu/flask-session-cookie-manager# pip install setuptools
Requirement already satisfied: setuptools in ./venvNew/lib/python3.10/site-packages (59.6.0)
(venvNew) root@hcss-ecs-b9f5:/home/lu/flask-session-cookie-manager# python -m pip install .
Processing /home/lu/flask-session-cookie-manager
  Preparing metadata (setup.py) ... done
Collecting Flask
  Using cached flask-3.1.0-py3-none-any.whl (102 kB)
Collecting itsdangerous
  Using cached itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Collecting Jinja2>=3.1.2
  Using cached jinja2-3.1.5-py3-none-any.whl (134 kB)
Collecting blinker>=1.9
  Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Collecting Werkzeug>=3.1
  Using cached werkzeug-3.1.3-py3-none-any.whl (224 kB)
Collecting click>=8.1.3
  Using cached click-8.1.8-py3-none-any.whl (98 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-3.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20 kB)
Using legacy 'setup.py install' for flask-session-cookie-manager, since package 'wheel' is not installed.
Installing collected packages: MarkupSafe, itsdangerous, click, blinker, Werkzeug, Jinja2, Flask, flask-session-cookie-manager
  Running setup.py install for flask-session-cookie-manager ... done
Successfully installed Flask-3.1.0 Jinja2-3.1.5 MarkupSafe-3.0.2 Werkzeug-3.1.3 blinker-1.9.0 click-8.1.8 flask-session-cookie-manager-1.2.1.1 itsdangerous-2.2.0
(venvNew) root@hcss-ecs-b9f5:/home/lu/flask-session-cookie-manager# python3 flask_session_cookie_manager3.py decode -s "84ea4ca9d7aa42709d5005e6f77acc73*abcdefgh" -c "eyJhZG1pbiI6MH0.Z21tOA.eM3OfG2t-09c10pSNufG_P2mPVs"
[Decoding error] 'MockApp' object has no attribute 'config'

**Comment by noraj** [comment] 2024-12-30 08:29
Duplicate of #14

**Closed by noraj** 2024-12-30 08:29 UTC
